"""
Configuration for meshcore-watchlist.

Paths and runtime settings.  Port and source-archive path can be
overridden via environment variables (set by the systemd unit
generated by install.sh).
"""

import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Version
# ---------------------------------------------------------------------------

VERSION: str = "0.3.3"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# Watchlist private state (channel definitions, tailer cursors, archive).
WATCHLIST_HOME = Path.home() / ".meshcore-watchlist"
WATCHLIST_FILE = WATCHLIST_HOME / "watchlist.json"
STATE_FILE = WATCHLIST_HOME / "state.json"
ARCHIVE_DIR = WATCHLIST_HOME / "archive"

# Source: meshcore-gui's archive directory.  Tailer reads *_rxlog.jsonl
# files from this directory.  Override via MESHCORE_GUI_ARCHIVE env var.
SOURCE_ARCHIVE_DIR = Path(
    os.environ.get(
        "MESHCORE_GUI_ARCHIVE",
        str(Path.home() / ".meshcore-gui" / "archive"),
    )
)

# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------

PORT: int = int(os.environ.get("MESHCORE_WATCHLIST_PORT", "8083"))
HOST: str = os.environ.get("MESHCORE_WATCHLIST_HOST", "0.0.0.0")

# ---------------------------------------------------------------------------
# Tailer
# ---------------------------------------------------------------------------

TAILER_POLL_SECONDS: float = 1.0

# ---------------------------------------------------------------------------
# Retention (mirrors meshcore-gui defaults)
# ---------------------------------------------------------------------------

MESSAGE_RETENTION_DAYS: int = 7
RXLOG_RETENTION_DAYS: int = 7

# ---------------------------------------------------------------------------
# Public channel
# ---------------------------------------------------------------------------
# The MeshCore Public channel does NOT follow the SHA-256(name)[:16]
# derivation rule that hashtag channels use.  In the firmware its
# secret slot is represented as 16 zero bytes (see Companion Protocol
# SET_CHANNEL spec) but on-air encryption uses a fixed well-known
# 16-byte secret, hard-coded in the firmware and reference decoders.
#
# We register that secret directly when a watchlist entry is named
# "Public" (case-insensitive).  If the firmware ever rotates this
# value, change it here in one place.
#
# Source of the current value: michaelhart/meshcore-decoder
# (TypeScript) and the matching Python meshcoredecoder package, both
# of which list it as the Public-channel test secret.

PUBLIC_CHANNEL_CANONICAL_NAME: str = "Public"
PUBLIC_CHANNEL_SECRET_HEX: str = "8b3387e9c5cdea6ac9e5edbaa115cd72"
PUBLIC_CHANNEL_SECRET: bytes = bytes.fromhex(PUBLIC_CHANNEL_SECRET_HEX)


def is_public_channel_name(name: str) -> bool:
    """True iff ``name`` refers to the MeshCore Public channel.

    Case-insensitive; tolerates a stray leading ``#`` from older
    watchlist files where ``WatchlistStore.add()`` force-prefixed
    every name.
    """
    if not name:
        return False
    stripped = name.lstrip("#").strip().lower()
    return stripped == PUBLIC_CHANNEL_CANONICAL_NAME.lower()


# ---------------------------------------------------------------------------
# Debug
# ---------------------------------------------------------------------------

DEBUG: bool = os.environ.get("MESHCORE_WATCHLIST_DEBUG", "0") == "1"


def debug_print(*args, **kwargs) -> None:
    """Print to stderr only when DEBUG is enabled."""
    if DEBUG:
        print("[watchlist]", *args, file=sys.stderr, **kwargs)
