"""
Configuration for meshcore-watchlist.

Paths and runtime settings.  Port and source-archive path can be
overridden via environment variables (set by the systemd unit
generated by install.sh).
"""

import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Version
# ---------------------------------------------------------------------------

VERSION: str = "0.3.8"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# Watchlist private state (channel definitions, tailer cursors, archive).
WATCHLIST_HOME = Path.home() / ".meshcore-watchlist"
WATCHLIST_FILE = WATCHLIST_HOME / "watchlist.json"
STATE_FILE = WATCHLIST_HOME / "state.json"
ARCHIVE_DIR = WATCHLIST_HOME / "archive"

# Source: meshcore-gui's archive directory.  Tailer reads *_rxlog.jsonl
# files from this directory.  Override via MESHCORE_GUI_ARCHIVE env var.
SOURCE_ARCHIVE_DIR = Path(
    os.environ.get(
        "MESHCORE_GUI_ARCHIVE",
        str(Path.home() / ".meshcore-gui" / "archive"),
    )
)

# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------

PORT: int = int(os.environ.get("MESHCORE_WATCHLIST_PORT", "8083"))
HOST: str = os.environ.get("MESHCORE_WATCHLIST_HOST", "0.0.0.0")

# ---------------------------------------------------------------------------
# Tailer
# ---------------------------------------------------------------------------

TAILER_POLL_SECONDS: float = 1.0

# Upper bound on the backwards search the tailer performs when it finds
# its source file rewritten.  The last consumed line is normally within
# a few kilobytes of EOF, so this only caps the pathological case: if
# the line is not found within this many bytes the tailer gives up and
# replays the file from the start.
TAILER_RESYNC_MAX_BYTES: int = 64 * 1024 * 1024

# Upper bound on how long the shutdown hook waits for the archive lock
# before giving up and letting the process exit.  Must stay well inside
# systemd's TimeoutStopSec (90s by default) so the service always stops
# cleanly rather than being SIGKILLed.
SHUTDOWN_FLUSH_TIMEOUT_SECONDS: float = 15.0

# Render GUI timestamps in the machine's local timezone rather than UTC.
# The archive and the REST API both speak UTC (ADR-002) and are not
# affected; this only changes what the dashboard displays, so it matches
# the downstream collector's local rendering instead of showing the same
# packet two hours apart on two screens.
GUI_TIMESTAMPS_LOCAL: bool = True

# ---------------------------------------------------------------------------
# Retention (mirrors meshcore-gui defaults)
# ---------------------------------------------------------------------------

MESSAGE_RETENTION_DAYS: int = 7
RXLOG_RETENTION_DAYS: int = 7

# Retention is NOT applied by the daemon.  ``cleanup_old_data()`` rewrites
# both archive files end to end; on a 600 MB rxlog that is minutes of
# json.loads/json.dumps, which holds the GIL and the archive lock and
# leaves the NiceGUI event loop unable to answer a single request.  0.3.6
# ran it on the startup path and 0.3.7 tried a background thread — both
# stalled the service, because the work does not belong in this process
# at all.  Run ``purge_archive.py`` from cron instead; these two values
# are the window it defaults to.

# ---------------------------------------------------------------------------
# Public channel
# ---------------------------------------------------------------------------
# The MeshCore Public channel does NOT follow the SHA-256(name)[:16]
# derivation rule that hashtag channels use.  In the firmware its
# secret slot is represented as 16 zero bytes (see Companion Protocol
# SET_CHANNEL spec) but on-air encryption uses a fixed well-known
# 16-byte secret, hard-coded in the firmware and reference decoders.
#
# We register that secret directly when a watchlist entry is named
# "Public" (case-insensitive).  If the firmware ever rotates this
# value, change it here in one place.
#
# Source of the current value: michaelhart/meshcore-decoder
# (TypeScript) and the matching Python meshcoredecoder package, both
# of which list it as the Public-channel test secret.

PUBLIC_CHANNEL_CANONICAL_NAME: str = "Public"
PUBLIC_CHANNEL_SECRET_HEX: str = "8b3387e9c5cdea6ac9e5edbaa115cd72"
PUBLIC_CHANNEL_SECRET: bytes = bytes.fromhex(PUBLIC_CHANNEL_SECRET_HEX)


def is_public_channel_name(name: str) -> bool:
    """True iff ``name`` refers to the MeshCore Public channel.

    Case-insensitive; tolerates a stray leading ``#`` from older
    watchlist files where ``WatchlistStore.add()`` force-prefixed
    every name.
    """
    if not name:
        return False
    stripped = name.lstrip("#").strip().lower()
    return stripped == PUBLIC_CHANNEL_CANONICAL_NAME.lower()


# ---------------------------------------------------------------------------
# Debug
# ---------------------------------------------------------------------------

DEBUG: bool = os.environ.get("MESHCORE_WATCHLIST_DEBUG", "0") == "1"


def debug_print(*args, **kwargs) -> None:
    """Print to stderr only when DEBUG is enabled."""
    if DEBUG:
        print("[watchlist]", *args, file=sys.stderr, **kwargs)
