"""
Configuration for meshcore-watchlist.

Paths and runtime settings.  Port and source-archive path can be
overridden via environment variables (set by the systemd unit
generated by install.sh).
"""

import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Version
# ---------------------------------------------------------------------------

VERSION: str = "0.2.0"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# Watchlist private state (channel definitions, tailer cursors, archive).
WATCHLIST_HOME = Path.home() / ".meshcore-watchlist"
WATCHLIST_FILE = WATCHLIST_HOME / "watchlist.json"
STATE_FILE = WATCHLIST_HOME / "state.json"
ARCHIVE_DIR = WATCHLIST_HOME / "archive"

# Source: meshcore-gui's archive directory.  Tailer reads *_rxlog.jsonl
# files from this directory.  Override via MESHCORE_GUI_ARCHIVE env var.
SOURCE_ARCHIVE_DIR = Path(
    os.environ.get(
        "MESHCORE_GUI_ARCHIVE",
        str(Path.home() / ".meshcore-gui" / "archive"),
    )
)

# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------

PORT: int = int(os.environ.get("MESHCORE_WATCHLIST_PORT", "8083"))
HOST: str = os.environ.get("MESHCORE_WATCHLIST_HOST", "0.0.0.0")

# ---------------------------------------------------------------------------
# Tailer
# ---------------------------------------------------------------------------

TAILER_POLL_SECONDS: float = 1.0

# ---------------------------------------------------------------------------
# Retention (mirrors meshcore-gui defaults)
# ---------------------------------------------------------------------------

MESSAGE_RETENTION_DAYS: int = 7
RXLOG_RETENTION_DAYS: int = 7

# ---------------------------------------------------------------------------
# Debug
# ---------------------------------------------------------------------------

DEBUG: bool = os.environ.get("MESHCORE_WATCHLIST_DEBUG", "0") == "1"


def debug_print(*args, **kwargs) -> None:
    """Print to stderr only when DEBUG is enabled."""
    if DEBUG:
        print("[watchlist]", *args, file=sys.stderr, **kwargs)
